---
title: "International Students"
---

## Scholarships and Exchange Programs

::: {.panel-tabset}

### Undergraduate

##### [France International Mobility Program](https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/francophone-mobility.html)

- The Francophone mobility work permit makes it easier for Canadian employers to hire you without a labour market impact assessment.

##### [ELAP](https://www.scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/elap-pfla.aspx?lang=eng)

- Undergraduate and graduate students from the Caribbean and South America.

##### [Canada-ASEAN Scholarships and Educational Exchanges for Development (SEED)](https://scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/asean-anase.aspx?lang=eng
)

- Undergraduate and graduate students from ASEAN member states.

##### [China Scholarship Council (CSC) Funded Internships](https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/csc-funded-placements/index.html)

- The China Scholarship Council provides funding to undergraduate students
from Double First-Class Initiative universities in China to conduct
research ­at UAlberta under the supervision of faculty members who are
experts in their field.

##### [Study in Canada Scholarships](https://www.educanada.ca/scholarships-bourses/can/institutions/study-in-canada-sep-etudes-au-canada-pct.aspx?lang=eng)

- Undergraduate and graduate students from: Asia: Bangladesh, Nepal,
Taiwan; Europe: Turkey, Ukraine; The Middle East and North Africa:
Algeria, Egypt, Jordan, Libya, Morocco, Tunisia; Sub-Saharan Africa:
Burkina Faso, Ethiopia, Ghana, Ivory Coast, Kenya, Nigeria, Rwanda,
Senegal, Tanzania, and Uganda.

##### [UARE](https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/ualberta-research-experience/index.html)

- The UARE provides a unique opportunity for talented senior undergraduate
students from key partner universities around the world to conduct research
under the supervision of faculty members who are experts in their field.

##### [Mitacs Globalink](https://www.mitacs.ca/en/programs/globalink)

- Take your research abroad with Mitacs Globalink. Globalink offers travel funding between Canada and several international partners.

### Graduate

##### [Emerging Leaders in the Americas Program (ELAP)](https://www.scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/elap-pfla.aspx?lang=eng)

- Undergraduate and graduate students from the Caribbean and South America.

##### [Canada-ASEAN Scholarships and Educational Exchanges for Development (SEED)](https://scholarships-bourses.gc.ca/scholarships-bourses/can/institutions/asean-anase.aspx?lang=eng)

- Undergraduate and graduate students from ASEAN member states.

##### [China Scholarship Council (CSC) Funded Internships](https://www.ualberta.ca/admissions-programs/visiting-student-and-internship-programs/research-internships/csc-funded-placements/index.html)

- The China Scholarship Council provides funding to undergraduate students from Double First-Class Initiative universities in China to conduct research ­at UAlberta under the supervision of faculty members who are experts in their field.

##### [Study in Canada Scholarships](https://www.educanada.ca/scholarships-bourses/can/institutions/study-in-canada-sep-etudes-au-canada-pct.aspx?lang=eng)

- Undergraduate and graduate students from: Asia: Bangladesh, Nepal, Taiwan;
Europe: Turkey, Ukraine; The Middle East and North Africa: Algeria, Egypt,
Jordan, Libya, Morocco, Tunisia; Sub-Saharan Africa: Burkina Faso, Ethiopia,
Ghana, Ivory Coast, Kenya, Nigeria, Rwanda, Senegal, Tanzania, and Uganda.

##### [Rocca](https://www.robertorocca.org/en)

- Scholarships to exceptional university graduates, with the aim of
helping them finance doctoral studies in the areas of Materials Science,
Mechanical Engineering, Metallurgical Engineering and Petroleum
Engineering, at a university outside their country of origin.

- Roberto Rocca Fellowships are open to students who are citizens of
Argentina, Brazil, Uruguay, Colombia, Indonesia, Saudi Arabia, Mexico
and Romania, and who will enter a Ph.D. program outside their own
country or who have already begun their studies towards a Ph.D. at a
university outside their own country. Application of citizens of these
countries, living in other of these countries may be accepted too.

##### [CSC](http://apply.csc.edu.cn/)

- The China Scholarship Council (CSC) is a government agency in China
which provides scholarships to students for doctoral and postdoctoral
studies abroad. These scholarships will be awarded to students across a
wide range of disciplines.

##### [AWS](https://www.aws.org/foundation/page/research-fellowships)

- Fellowship from The American Welding Society (AWS) Foundation, which
seeks to foster university research in joining and to recognize
outstanding faculty and student talent.

:::

[Request a Letter of Invitation for International Scholarships Programs](https://docs.google.com/forms/d/e/1FAIpQLSdnuXjmbKJ3WsKJLbEDW8y9QWIVFE8EBQRsCgKJw_5XLUcqQA/viewform)
